### ISSUE TITLE
Смешиваются модели для DTO и DBO

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#1]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/data/model/Movie.kt#L17

1) Тут в модели фильма смешаны аннотации для GSON и Room. С точки зрения архитектуры и масштабирования это не оч хорошо. Обычно разделяют модели данных которые нужны для сетевого слоя и те, которые нужны для работы БД.
И потом они уже конвертятся например в Domain Object - то есть то, что потом используется внутри приложения для presentation/domain слоя. 

Для простого приложения это может казаться усложнением - но для больших систем, там такое разделение упрощает разработку и масштабирование.

Советую вот это https://medium.com/android-dev-hacks/detailed-guide-on-android-clean-architecture-9eab262a9011
И вот https://habr.com/ru/company/mobileup/blog/335382/

2) Еще в сетевых моделях почти все поля requered - то есть не опциональные (без ?) Это значит что если сервер не вернет какое то поле - то будет сразу краш. Поэтому мы обычно в нашем приложении стараемся почти все делать опциональными полями в моделях ответа. В случае с MovieDatabase API скорее всего вряд ли будет такая ситуация - но обычно стараются поля ответа делать опциональными, если нет 200% уверенности в ответе и в полях.

**Comment by dalapenko** [comment]
Растащил Movie на DBO и DTO в рамках PR #17 

Добавил мапперы которые гоняют модели между Model/DBO/DTO

В DTO сделал все поля опциональными
