### ISSUE TITLE
Использование DataBinding

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#10]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/res/layout/fragment_main.xml#L6

Обычно databinding стараются не использовать - это можно сказать антипатерн. Проблема в том что он очень легко позволяет нарушить Single Responsibility и вместо того чтобы layout просто отображал данные - он уже содержит бизнес-логику.

**Comment by dalapenko** [comment]
Избавился от Data binding в https://github.com/dalapenko/the-watcher-app/pull/14
