### ISSUE TITLE
Размеры/цвета/строки нужно выносить в ресурсы

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#11]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/res/layout/fragment_card.xml#L81

Размеры/цвета/строки обычно выносят в ресурсы. Размеры в dimens.xml, цвета в colors.xml
Если у UI компонентов повторяются атрибуты (цвет/стиль например для текста) то одинаковые наборы атрибутов выносят в стили и потом применяю уже стили к конкретным виджетам

**Comment by dalapenko** [comment]
Поправил в МР https://github.com/dalapenko/the-watcher-app/pull/12
