### ISSUE TITLE
exportScema=false

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#2]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/data/local/MovieDatabase.kt#L10

А кстати почему поставил false?
Эта штука может пригодится при написании тестов при Миграции БД
https://developer.android.com/training/data-storage/room/migrating-db-versions#:~:text=Export%20schemas,CommandLineArgumentProvider%20that%20provides%20the%20room.

**Comment by dalapenko** [comment]
Тут всё просто, т.к. раньше не работал с room прочитал из описания, что exportSchema можно отключить если не планируем хранить версионирование. Для демонстрационного проекта решил поставить false

`
Value of exportSchema is true by default but you can disable it for databases when you don't want to keep history of versions (like an in-memory only database).
`
