### ISSUE TITLE
Вынести в константы

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#4]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/data/remote/MovieApi.kt#L22

ru-RU и номер страницы можно вынести в соответствующие константы

**Comment by dalapenko** [comment]
Вытащил в PR https://github.com/dalapenko/the-watcher-app/pull/13
