### ISSUE TITLE
LiveData в репозитории

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#5]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/data/repository/MovieRepository.kt#L25

LiveData не рекомендуется использовать в репозиториях. 
https://proandroiddev.com/no-more-livedata-in-your-repository-there-are-better-options-25a7557b0730
Максимум в ViewModel и то от нее сейчас отказываются и вместо нее Flow.

Тут надо 
1) Избавиться от LiveData
2) Сделать методы репозитория чтобы они были либо suspend-функциями  либо возвращали Flow
3) В интерфейсе ретрофита можно вообще методы сделать suspend
4) Убрать работу со скоупами. Сущности которые не имеют собственного ЖЦ не должны работать с скоупами. Достаточно чтобы в репозитории были методы (suspend или Flow) которые уже будет вызывать ViewModel и использовать там скоупы. Вот тут пример с корутинами - там Retrofit методы просто как suspend помечены. И есть пример offline first. Можно еще как вариант и так сделать https://github.com/amitshekhariitbhu/Learn-Kotlin-Coroutines

Метод deleteAll()  впринципе лишний - либо оставить movieDao.deleteAll() но не использовать скоупы
Для метода insertLocalData тоже не нужно скоупы использовать - этот вызов (     ioCoroutineScope.launch { movieDao.insertMovie(*movie) }) уже должен быть в ViewModel
Задача репозитория просто знать как отдать данные, а вся обвязка со скоупами должна быть уже во ViewModel
Нужно только чтобы репозиторий поддерживал работу корутин (имел suspend модификарторы или Flow)

Конструкция с dataSource сложная получилась. Если сделать все suspend функциями то это все не нужно будет.
А тут смесь и LiveData и Call<T> . 

И сам по себе репозиторий усложнен. Это больше похоже на Interactor. То есть можно было сделать 2 репозитория Remote  и Local, а интерактор уже как раз между ними какую-то логику добавляет.

**Comment by dalapenko** [comment]
Сделал всё согласно рекомендациям. Избавился от сложных конструкций, скоупов и LiveData в Repository. Перешел на suspend в api/dao и flow в repository.

Единственное исключение - insertMovie я все таки оставил в repository как приватный метод, т.к. в репозитории именно собралась вся логика получения данных и т.к. перешел на flow процесс стал такой - эмитим данные из БД, потом пытаемся получать новые из АПИ, если всё ок - обновляем данные в бд и эмитим обновленные значения. Кажется это ок
