### ISSUE TITLE
ViewModel возвращает LiveData

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#6]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/view/viewmodel/MovieViewModel.kt#L16

Тут ViewModel посути просто проксирует вызов репозитория который возращает LiveData. ViewModel должна общаться с UI через LiveData( или Flow) но не возвращать ее.
То есть надо создать переменную LiveData и через нее в ViewModel передавать данные которые приходят после вызовов метода репозитория. 
Просто как пример https://github.com/AndroidStudentClub/Android-LiveData-Demo/blob/feature/add-livedata-viewmodel-search/app/src/main/java/ru/mikhailskiy/livedata/MainViewModel.kt

**Comment by dalapenko** [comment]
Избавил от этого в PR #5
