### ISSUE TITLE
Метод ViewModel вызываются каждый раз при пересоздании фрагмента

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#7]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/java/tech/dalapenko/thewatcher/view/fragment/MainFragment.kt#L40

Тут есть метод setupFragmentLayouts() который будет вызываться каждый раз при вызове onCreateView.  Рекомендуется вызывать методы для изначальной инициализации экрана в блоке init{} во ViewModel. Это важно с точки зрения ЖЦ фрагмента и ViewModel. У ViewModel этот блок вызвыается 1 раз, в то время как у активити или фрагмента методы ЖЦ могут вызывать 100 500 раз. Поэтому разместив всю инициализирующую логику в init() мы не делаем лишние запросы и экономим ресурсы https://developer.android.com/topic/libraries/architecture/viewmodel#lifecycle

**Comment by dalapenko** [comment]
После изменений в рамках PR #5 теперь setup методы только отрисовывают нужные блоки без выполнения каких либо запросов. А запрос данных для начальной инициализации экрана уехала в init блок viewmodel. Вроде теперь норм

**Comment by dalapenko** [comment]
Немного поменялось поведение в PR #19, там большая часть логики связанная с созданием и настройкой сущностей уехала как раз во ViewModel
