### ISSUE TITLE
Лишние контейнеры

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#8]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/res/layout/activity_main.xml#L11
Тут скрол вью - он лишний, так как внутри него фрагмент. А фрагмент уже сам определяет как отобразить контент. Поэтому это лишние контейнеры.

**Comment by dalapenko** [comment]
Без обертки в NestedScrollView оно почему-то отказывается скролится по вертикали в landscape режиме

**Comment by dalapenko** [comment]
Решилось после перехода на отображение секций через группи в МР #15
