### ISSUE TITLE
Используется 3 RecyclerView

### ISSUE THREAD

**Issue by AndroidStudentClub** [dalapenko/the-watcher-app#9]
https://github.com/dalapenko/the-watcher-app/blob/efdeae9bc5a652a928443cf343d3637964546c3b/app/src/main/res/layout/fragment_main.xml#L31

Тут в верстке 3 RecyclerView. Обычно делают все через один RecyclerView. В данном случае это можно сделать используя разные типы ячеек. https://stackoverflow.com/questions/26245139/how-to-create-recyclerview-with-multiple-view-types
 
Например одна ячейка это заголовок секции а вторая ячейка 1) Либо скрол (но scrollview подойдет только для небольшого количества обложе фильмов например 3-4) 2) Либо если хочется сделать горизонтальный список то второй тип ячейки это еще один ресайклер. Получается будет один общий ресайклер вертикальный в котором будут ячейки заголовка и ячейка с горизонтальным ресайклером.

Точно такую схему я описывал вот тут в статье - правда там используется библиотека Groupie (у нас в проекте она тоже есть)
https://habr.com/ru/post/523768/

**Comment by dalapenko** [comment]
В качестве решения решил попробовать библиотеку Groupie, что бы разобраться с ней немного. В итоге заменил вложенные ресайклеры на вертикальный ресайклер с котором текст + горизонтальный ресайклер через Groupie. Сделано в рамках PR #15
